Class {
	#name : #MDCTabBarDemoScreen,
	#superclass : #MDCComponentDemo,
	#category : #'Material-Components-Demo-Components2'
}

{ #category : #accessing }
MDCTabBarDemoScreen class >> description [
	^ 'Tabs make it easy to explore and switch between different views.'
]

{ #category : #accessing }
MDCTabBarDemoScreen class >> icon [
	^ 'compTabsPng'
]

{ #category : #accessing }
MDCTabBarDemoScreen class >> title [
	^ 'Tab Bar'
]

{ #category : #accessing }
MDCTabBarDemoScreen >> actualClasses [
	^ {  }
]

{ #category : #rendering }
MDCTabBarDemoScreen >> renderScreenContentOn: html [
	
]
